export enum UserRole {
    LANDLORD = "ROLE_LANDLORD",
    TENANT = "ROLE_TENANT",
    ADMIN = "ROLE_ADMIN",
}

export enum AssetType {
    BOARDING_HOUSE = "BOARDING_HOUSE",
    SHARED_HOUSING_SYSTEM = "SHARED_HOUSING_SYSTEM",
    APARTMENT = "APARTMENT",
    DORMIROTY = "DORMITORY",
    STUDIO_APARTMENT = "STUDIO_APARTMENT",
    ENTIRE_HOUSE = "ENTIRE_HOUSE"
}
